name: Generate Snake Game

on:
 schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
 workflow_dispatch:

jobs:
 build:
    name: Generate Snake Game Animation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: codelover1226
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
